### PR TITLE
Add js head tap meme and dark kermit meme

### PR DESCRIPTION
**Pull request by loiralae**

### CODE REVIEW

**Comment by dianjin** [comment]
Love it! A few things:

* Could you use [this photo](https://19807-presscdn-pagely.netdna-ssl.com/wp-content/uploads/7dd/f2/f4ff8b0d242f954810eb3b609c747f31.jpg) instead? Your crop is different from other memes.
* [nit] Can you use Helvetica Neue Light? It should be an option in Pages...lmk if you can't find it.
* [nit] Can you decapitalize the first word?
* Can you remove "chrome"? Want to keep it browser-agnostic! 😃 
* If possible, could you insert a watermark onto the meme? I just pushed them to master. If you can't I'll do it after we merge.
* Feel free to commit the raw meme (photoshop file, MS word doc, whatever) to promote remixing.

To confirm, you'd like credit when I post on FB right?

Also, one meme per PR please! 😜 I think the dark kermit one is too specific though.

**Comment by loiralae** [comment]
fixed!

**Comment by dianjin** [comment]
* Can you make the meme bigger, like minimum 800px width?
* Can you remove the word "browser"?

**Comment by dianjin** [comment]
👍 Publishing tonight! Thanks for contributing 🌟

**Pull request merged**
